#!/usr/bin/env node

const fs = require('fs');
const TIMEOUT_THRESHOLD = 3000;
var emoji = require('node-emoji')

checkCommitMessage();
hookCleanup();

async function checkCommitMessage() {

    const message = fs.readFileSync(process.argv[2], 'utf8').trim();
    fs.writeFileSync(process.argv[2], emoji.emojify(message, (name) => name));
    process.exit(0);
}

function hookCleanup() {

    setTimeout(() => {
        console.log(' Algo de errado não está certo com o hook, sorry');
        console.log(' O Commit será rejeitado por questão de segurança');
        console.log(' Mais informações podem ser encontradas aqui: https://git-scm.com/book/uz/v2/Customizing-Git-An-Example-Git-Enforced-Policy');
        process.exit(1);
    }, TIMEOUT_THRESHOLD);

}